variables:
  PRI_REGISTRY: 192.168.250.75:5000
  WEB_IMAGE: linesum/devops/datahub/frontend-image
  DOCKER_BUILDER_IMAGE: test_datahub_builder_image
  DOCKER_BUILDER_RUNNER: test_datahub_builder_image_runner
  DOCKER_DIST_IMAGE: $PRI_REGISTRY/$WEB_IMAGE:dev
before_script:
  - echo "begin to run script"
stages:
  - dump
  - build
  - buildInter
  - buildQa
  - install
  - deploy
  - trigger

web:echo:
  stage: dump
  script:
    - echo $CI_BUILD_TAG
  only:
    - develop
    - tags    
    
web:dist:build:dev:
  stage: build 
  before_script:
    - docker stop $DOCKER_BUILDER_RUNNER && docker rm $DOCKER_BUILDER_RUNNER  
  script:
    - export TAG=dev
    - docker build -t $DOCKER_BUILDER_IMAGE --build-arg REACT_BASEURL=http://erp-qa.linesum.com -f ./Dockerfile.build .
    - docker stop $DOCKER_BUILDER_RUNNER && docker rm $DOCKER_BUILDER_RUNNER
    - docker run --name $DOCKER_BUILDER_RUNNER $DOCKER_BUILDER_IMAGE /bin/bash
    - docker cp $DOCKER_BUILDER_RUNNER:/src/app/dist ./docker/dist
    - docker build --pull -t $PRI_REGISTRY/$WEB_IMAGE:$TAG --build-arg CONT_IMG_VER=$TAG ./docker
    - docker push $PRI_REGISTRY/$WEB_IMAGE:$TAG
    - docker-compose up -d
  only:
    - develop
  after_script:
    - docker stop $DOCKER_BUILDER_RUNNER && docker rm $DOCKER_BUILDER_RUNNER
