FROM 192.168.250.75:5000/node

RUN npm config set registry https://registry.npm.taobao.org 

# Create app directory
RUN mkdir -p /src/app
WORKDIR /src/app

# to make npm test run only once non-interactively
ENV CI=true
# Install app dependencies
COPY package.json /src/app/
COPY yarn.lock /src/app/

RUN yarn install 

COPY . /src/app

ARG REACT_BASEURL 
ENV REACT_BASEURL ${REACT_BASEURL:-http://devops.qa.idea.linesum.com:18080}
RUN yarn run build
